### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by zhq1** [vagabondan/ric-nomp#1]
[root@vultr nomp]# node init.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'stratum-pool'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/nomp/libs/poolWorker.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by vagabondan** [comment]
Please try once again the following steps:
git pull
npm update --recursive
node init.js

**Comment by strataspool** [comment]
What node version are you using vagabondan?

**Comment by vagabondan** [comment]
@strataspool    6.11.2

**Comment by strataspool** [comment]
I get the same error as zhq1 Error: Cannot find module 'stratum-pool'
but when i edit the package.json file change "stratum-pool": "https://github.com/vagabondan/node-stratum-pool.git" to "stratum-pool": "git://github.com/vagabondan/node-stratum-pool.git"
i get the errors about the  multi-hashing module

**Comment by Kukks** [comment]
Doesn't work for me either @vagabondan I've tried a plethora of different versions of node to no luck. Always fails on the multi-hashing module.

**Comment by vagabondan** [comment]
@Kukks @strataspool guys, multihashing module is here: 
https://github.com/krisklosterman/node-multi-hashing
I suppose Kris has switched his node version and got many errors in result. Try to rollback version of multihashing prior the 3rd of October.

**Comment by vagabondan** [comment]
Changed dependencies from Kris to my repository... Hope it helps.

Please try once again the following steps:
git pull
npm update --recursive
node init.js

**Comment by strataspool** [comment]
It works for me now. I did:

rm -rf node_modules
npm update

**Comment by thepcb88** [comment]
Hot to fix this issue?

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/v0.10.47/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-25-generic
gyp ERR! command "node" "/root/.nvm/v0.10.47/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/nomp/node_modules/stratum-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.47
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 3.16.0-25-generic
npm ERR! argv "/root/.nvm/v0.10.47/bin/node" "/root/.nvm/v0.10.47/bin/npm" "update" "--recursive"
npm ERR! node v0.10.47
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@0.0.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/nomp/npm-debug.log

Im already tested rm -rf node_module && ../.node-gyp && npm update 
Tested with nodejs 0.10.47, 0.10.48, 8.0.0, 10.0.0 and 11.0.0
All versions print same error message.
